# Generated by Django 4.2.6 on 2024-06-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="game",
            name="link",
            field=models.CharField(default="", max_length=255),
        ),
    ]
