# Generated by Django 4.2.6 on 2024-06-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_description_game_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Imagem Capa do Jogo",
                null=True,
                upload_to="games/game/image",
                verbose_name="Capa",
            ),
        ),
    ]
